spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev
    application: 
      name: cloudConfig-dev

---
spring:
  profiles: test
    application: 
      name: cloudConfig-test

#utf-8