spring:
  profiles:
    active:
    - dev

---
server:
  port: 10001
spring:
  profiles: dev
  application:
    name: service-application-config-client
eureka:
  client:
    service-url:
       defaultZone: http://local10001-dev.com:10001/eureka/

---
server:
  port: 10002
spring:
  profiles: test
  application:
    name: service-application-config-client
eureka:
  client:
    service-url:
       defaultZone: http://local10002-test.com:10002/eureka/
#utf-8