spring:
  profiles:
    active:
    - dev

---
server:
  port: 10003
spring:
  profiles: dev
  application:
    name: service-application-config-client
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
       defaultZone: http://localhost:10003/eureka/

---
server:
  port: 10002
spring:
  profiles: test
  application:
    name: service-application-config-client
eureka:
  client:
    service-url:
       defaultZone: http://localhost:10002/eureka/
#utf-8